### ISSUE TITLE
Failed to display Swap in Memory Usage widget

### ISSUE THREAD

**Issue by aofei** [cjbassi/ytop#101]
Required information:

- ytop version (`ytop -V`): ytop 0.6.2
- The output of `uname -a`: Linux as-raspberry-pi 5.4.50-1-ARCH #1 SMP PREEMPT Sun Jul 12 20:24:24 MDT 2020 aarch64 GNU/Linux

Include any of the following information if relevant:

- Terminal emulator (e.g. iTerm or gnome terminal): [Blink](https://blink.sh)
- tmux version (`tmux -V`): tmux 3.1b
- Any relevenat hardware info: Raspberry Pi 4 Model B (8GB RAM)

Please copy or attach `~/.local/state/ytop/errors.log` if it exists and contains logs: null

---

As shown in the snaoshot below, the `ytop` failed to display `Swap` in the `Memory Usage` widget. BTW, the `gotop` can display it normally.

![66DC0540-A4CA-415E-84E1-30C709DB6FFB](https://user-images.githubusercontent.com/5037285/88092268-d1ab9b80-cbc2-11ea-8d3b-6f5900cb0d01.png)

**Comment by CosmicHorrorDev** [comment]
I'm having a hard time reproducing this, but I only have a Pi 2 instead of a Pi 4 currently. Can you tell me:

* What's the output of `free -h`?
* What OS are you running (seeing `pacman` makes me think ALARM)?
* Is this running within `ssh` since I see it on the process list?

**Comment by aofei** [comment]
> * What's the output of `free -h`?

```
              total        used        free      shared  buff/cache   available               
Mem:          7.6Gi       885Mi       1.6Gi       3.0Mi       5.1Gi       6.9Gi               
Swap:            0B          0B          0B
```

> * What OS are you running (seeing `pacman` makes me think ALARM)?

Yes, I'm using [Arch Linux ARM](https://archlinuxarm.org).

> * Is this running within `ssh` since I see it on the process list?

More precisely, it's [Mosh](https://mosh.org).

**Comment by CosmicHorrorDev** [comment]
Oh thank you for the very fast response! From the output of `free` I see you don't actually have any swap and `ytop` doesn't display swap if there isn't any.

**Comment by CosmicHorrorDev** [comment]
And mosh seems pretty interesting. I currently use `ssh` + `tmux` for keeping a session active that's going to last longer than a single `ssh` session, so I'll have to check it out and compare

**Comment by aofei** [comment]
> ... `ytop` doesn't display swap if there isn't any.

I thought `ytop` should be consistent with `gotop` (since they're from the same author).

Okay, I see, thank you for your answer. ❤️
