### ISSUE TITLE
no `memory` in the root

### ISSUE THREAD

**Issue by for-coursera** [cjbassi/ytop#11]
Required information:

- rtop version: 12407d3
- `uname -a`: Darwin [....] 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
- `rustc -V`: rustc 1.38.0 (625451e37 2019-09-23

Got the following error while compiling:

       Compiling rtop v0.1.0 (/Users/me/Desktop/rtop)
         Running `rustc --edition=2018 --crate-name rtop src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=aba14883eeb406ee -C extra-filename=-aba14883eeb406ee --out-dir /Users/s/Desktop/rtop/target/release/deps -L dependency=/Users/s/Desktop/rtop/target/release/deps --extern chrono=/Users/s/Desktop/rtop/target/release/deps/libchrono-e498a654cf3704ae.rlib --extern crossbeam_channel=/Users/s/Desktop/rtop/target/release/deps/libcrossbeam_channel-a692bd68cff0cda6.rlib --extern crossbeam_utils=/Users/s/Desktop/rtop/target/release/deps/libcrossbeam_utils-e8737c6e9ce0986b.rlib --extern crossterm=/Users/s/Desktop/rtop/target/release/deps/libcrossterm-723a43d17e550d68.rlib --extern ctrlc=/Users/s/Desktop/rtop/target/release/deps/libctrlc-e7cfec5e29607b78.rlib --extern fern=/Users/s/Desktop/rtop/target/release/deps/libfern-e2716a0298cca3c5.rlib --extern hostname=/Users/s/Desktop/rtop/target/release/deps/libhostname-b119cdf516e931de.rlib --extern lazy_static=/Users/s/Desktop/rtop/target/release/deps/liblazy_static-8ccaa296b22a542d.rlib --extern log=/Users/s/Desktop/rtop/target/release/deps/liblog-dd66067e563cdb60.rlib --extern num_rational=/Users/s/Desktop/rtop/target/release/deps/libnum_rational-42df8a57f346bce2.rlib --extern num_cpus=/Users/s/Desktop/rtop/target/release/deps/libnum_cpus-bdd7087efbc30a94.rlib --extern platform_dirs=/Users/s/Desktop/rtop/target/release/deps/libplatform_dirs-015382cb902e54c8.rlib --extern psutil=/Users/s/Desktop/rtop/target/release/deps/libpsutil-c3b02222cdd5c21c.rlib --extern serde=/Users/s/Desktop/rtop/target/release/deps/libserde-20a76b5029c9b462.rlib --extern serde_json=/Users/s/Desktop/rtop/target/release/deps/libserde_json-8486bd8264846271.rlib --extern size=/Users/s/Desktop/rtop/target/release/deps/libsize-1bbeba4119c95ce7.rlib --extern structopt=/Users/s/Desktop/rtop/target/release/deps/libstructopt-cb3af379cbbb3f70.rlib --extern tui=/Users/s/Desktop/rtop/target/release/deps/libtui-93165cf992917f51.rlib`
    error[E0432]: unresolved import `psutil::memory`
     --> src/widgets/mem.rs:2:5
      |
    2 | use psutil::memory;
      |     ^^^^^^^^^^^^^^ no `memory` in the root
    
    warning: unused import: `MouseEvent`
      --> src/main.rs:14:56
       |
    14 | use crossterm::{AlternateScreen, InputEvent, KeyEvent, MouseEvent};
       |                                                        ^^^^^^^^^^
       |
       = note: `#[warn(unused_imports)]` on by default
    
    error: aborting due to previous error
    
    For more information about this error, try `rustc --explain E0432`.
    error: Could not compile `rtop`.
    
    Caused by:
      process didn't exit successfully: `rustc --edition=2018 --crate-name rtop src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=aba14883eeb406ee -C extra-filename=-aba14883eeb406ee --out-dir /Users/s/Desktop/rtop/target/release/deps -L dependency=/Users/s/Desktop/rtop/target/release/deps --extern chrono=/Users/s/Desktop/rtop/target/release/deps/libchrono-e498a654cf3704ae.rlib --extern crossbeam_channel=/Users/s/Desktop/rtop/target/release/deps/libcrossbeam_channel-a692bd68cff0cda6.rlib --extern crossbeam_utils=/Users/s/Desktop/rtop/target/release/deps/libcrossbeam_utils-e8737c6e9ce0986b.rlib --extern crossterm=/Users/s/Desktop/rtop/target/release/deps/libcrossterm-723a43d17e550d68.rlib --extern ctrlc=/Users/s/Desktop/rtop/target/release/deps/libctrlc-e7cfec5e29607b78.rlib --extern fern=/Users/s/Desktop/rtop/target/release/deps/libfern-e2716a0298cca3c5.rlib --extern hostname=/Users/s/Desktop/rtop/target/release/deps/libhostname-b119cdf516e931de.rlib --extern lazy_static=/Users/s/Desktop/rtop/target/release/deps/liblazy_static-8ccaa296b22a542d.rlib --extern log=/Users/s/Desktop/rtop/target/release/deps/liblog-dd66067e563cdb60.rlib --extern num_rational=/Users/s/Desktop/rtop/target/release/deps/libnum_rational-42df8a57f346bce2.rlib --extern num_cpus=/Users/s/Desktop/rtop/target/release/deps/libnum_cpus-bdd7087efbc30a94.rlib --extern platform_dirs=/Users/s/Desktop/rtop/target/release/deps/libplatform_dirs-015382cb902e54c8.rlib --extern psutil=/Users/s/Desktop/rtop/target/release/deps/libpsutil-c3b02222cdd5c21c.rlib --extern serde=/Users/s/Desktop/rtop/target/release/deps/libserde-20a76b5029c9b462.rlib --extern serde_json=/Users/s/Desktop/rtop/target/release/deps/libserde_json-8486bd8264846271.rlib --extern size=/Users/s/Desktop/rtop/target/release/deps/libsize-1bbeba4119c95ce7.rlib --extern structopt=/Users/s/Desktop/rtop/target/release/deps/libstructopt-cb3af379cbbb3f70.rlib --extern tui=/Users/s/Desktop/rtop/target/release/deps/libtui-93165cf992917f51.rlib` (exit code: 1)

**Comment by cjbassi** [comment]
Are you running `cargo run`? I don't get this error when running that on my machine.

**Comment by cjbassi** [comment]
Oh, the issue is that you're on macOS and rust-psutil currently only works on Linux. The main thing I'm working on right now is actually implementing the necessary functions in rust-psutil since it's pretty barebones right now.

**Comment by for-coursera** [comment]
I see.

OK, let's wait :) Closing this?

**Comment by cjbassi** [comment]
Sounds good :) Also I just opened #12 to track rust-psutil progress.
