### ISSUE TITLE
process filtering doesn't work

### ISSUE THREAD

**Issue by sumanthratna** [cjbassi/ytop#114]
when I try searching processes, nothing happens

# Environment Information
- ytop 0.6.2
- `uname -a`: `Darwin SumanthRatnasAir 20.0.0 Darwin Kernel Version 20.0.0: Fri Aug 14 00:25:13 PDT 2020; root:xnu-7195.40.44.151.1~4/RELEASE_X86_64 x86_64`
- Terminal emulator (e.g. iTerm or gnome terminal): n/a, Terminal.app
- macOS Big Sur Beta

# Reproduction
1. `ytop`
2. type `/` (UI doesn't change)
3. type `s` (UI doesn't change)
4. hit enter (UI doesn't change)

5. type `/` (UI doesn't change)
6. type `sq` (ytop quits because of `q`)

**Comment by CosmicHorrorDev** [comment]
This is likely because process filtering isn't implemented in `ytop` yet.

_Reference: #47_

**Comment by sumanthratna** [comment]
whoops ;) didn't see that in the README

closing as a duplicate

**Comment by CosmicHorrorDev** [comment]
No problem! It can hard to keep track of all the issues. I'm also hoping process filtering gets added sometime soon!
