### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by cjbassi** [cjbassi/ytop#12]
Currently [rust-psutil](https://github.com/borntyping/rust-psutil) is pretty barebones so we need to implement a lot the necessary cross platform functionality. Also, ytop currently only compiles on Linux because only Linux functions are implemented.

- [x] Refactor rust-psutil to be more modular and allow cross platform functionality: https://github.com/borntyping/rust-psutil/pull/54
- [x] Implement the functionality on Linux x86
    - [x] temperatures
- [ ] Implement the functionality on macOS x86
    - [x] cpu percents
    - [x] cpu count
    - [x] memory
    - [ ] temps
    - [ ] disk
    - [x] net
    - [ ] processes
    - [x] battery

**Comment by cjbassi** [comment]
Step 1 is mostly done now, just waiting for review and merge.

**Comment by cjbassi** [comment]
Step 2 is also done now.

**Comment by for-coursera** [comment]
(Just for the record: can confirm it does crash on macOS when compiling :))

**Comment by cjbassi** [comment]
Yah, the macos ci would agree with you :). Btw if anyone wants to add macos support, feel free to port [heim's](https://github.com/heim-rs/heim) macos functions to rust-psutil and open a PR against my branch here: https://github.com/cjbassi/rust-psutil/tree/restructure.

edit: my PR was merged so you can open a PR against the main repo now.

**Comment by cjbassi** [comment]
@for-coursera I've been doing some macos work, can you test that it works now?

**Comment by for-coursera** [comment]
@cjbassi, thanks for your efforts!

It compiles with a few warnings (`rustc 1.40.0 (73528e339 2019-12-16)`, `rustup 1.21.1 (7832b2ebe 2019-12-20)`):

    [...]
    Compiling ytop v0.2.0
    warning: unused import: `psutil::sensors`
     --> src/widgets/temp.rs:2:5
      |
    2 | use psutil::sensors;
      |     ^^^^^^^^^^^^^^^
      |
      = note: `#[warn(unused_imports)]` on by default
    
    warning: field is never used: `collector`
      --> src/widgets/disk.rs:35:2
       |
    35 |     collector: disk::DiskIoCountersCollector,
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: `#[warn(dead_code)]` on by default
    
    warning: field is never used: `interfaces`
      --> src/widgets/net.rs:18:2
       |
    18 |     interfaces: &'b str,
       |     ^^^^^^^^^^^^^^^^^^^
    
        Finished dev [unoptimized + debuginfo] target(s) in 6m 16s

And everything seems to be OK except the process filtering (this `/` hotkey) doesn't seem to function :)

**Comment by bombsimon** [comment]
@for-coursera: Are you building this from `master`? I tried to build from that branch just now and I still don't have the disk usage or temperatures working.

Btw if it's of interest I get the same errors as posted above (same version of `rustc` and `rustup`, macOS 10.15.1).

**Comment by martinlindhe** [comment]
@bombsimon, see the first post for macOS status.

**Comment by bombsimon** [comment]
@martinlindhe Sorry if I'm stupid but the first post doesn't mention the branch where progress is made. 

@cjbassi posted 23 hours ago:

> I've been doing some macos work, can you test that it works now?

To which @for-coursera responded:

> And everything seems to be OK except the process filtering (this / hotkey) doesn't seem to function :)

I assumed that "everything" in this cases included disk usage and temperatures so that's why I asked for the branch instead of just waiting for the box to be ticked.

**Comment by martinlindhe** [comment]
@bombsimon The first post shows checkboxes of what is done on macOS support. This is already in the master branch.

**Comment by bombsimon** [comment]
@martinlindhe Yeah I saw the checkboxes but obviously i misunderstood what everything except the process filtering ment. I'll keep an eye on the checkboxes in the future instead. Thanks.

**Comment by cjbassi** [comment]
Yeah so temperatures and disk usage are not implemented yet for Macos. And the progress that has been made has been in rust-psutil and merged into ytop master.

**Comment by cjbassi** [comment]
I just added Macos disk usage support to master. Can someone test that it works?

**Comment by bombsimon** [comment]
@cjbassi Works like a charm! Thanks!

![image](https://user-images.githubusercontent.com/3248948/73109684-24521680-3f04-11ea-8422-7d2f66719763.png)

**Comment by cjbassi** [comment]
I'm going to go ahead and close this. I've documented which features are missing on Mac in the readme, and in order to implement them we need to do that in rust-psutil.
