### ISSUE TITLE
There is already an application named rtop

### ISSUE THREAD

**Issue by tydog98** [cjbassi/ytop#15]
[Here it is](http://www.rtop-monitor.org/). This could cause confusion in trying to find the project.

**Comment by cjbassi** [comment]
Hmm, that's unfortunate. Doesn't look like it's been maintained in a while tho. Should we still change the name? I'm open to suggestions if so. Could probably just choose a different letter to prefix 'top', like atop or something.

**Comment by cjbassi** [comment]
Already taken: atop, ctop, gtop, htop, ntop, ptop, qtop, rtop, utop, vtop.

stop is probably a no go XD

**Comment by alicektx** [comment]
...cjtop / cjbtop maybe? :-)

Have you seen [this](https://github.com/ClementTsang/bottom) btw? 
Maybe you guys would like to collaborate or exchange ideas etc etc...

All the best

**Comment by piegamesde** [comment]
What kind of name are you looking for? Is it really that important that i's short and contains `top`? I'd consider taking something more unique and memorable – if it's too long users can still alias it to `top`.

**Comment by cjbassi** [comment]
@alicektx Yah, I actually just saw that yesterday and just messaged him to see if we could join forces. :rocket:

**Comment by cjbassi** [comment]
@piegamesde Yah, I'm open to other ideas too, it doesnt have to have top in it.

**Comment by cjbassi** [comment]
Also, theres https://github.com/joprice/itop too, who I also messaged about collaborating.

**Comment by cjbassi** [comment]
I'm gonna go ahead and rename it to ytop at least for the time being but I'm still open to other ideas too.
