### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by cjbassi** [cjbassi/ytop#18]
Think its due to process fetching. Should be fixed if we use/implement the psutil oneshot api. https://github.com/borntyping/rust-psutil/issues/60

**Comment by jeffw387** [comment]
You probably already knew this but I suspect it's not actually using all that CPU. Running gotop and ytop next to each other makes it look like ytop is over-reporting its own usage, and somehow reporting reduced usage for all the other processes.

Gotop is on the left, ytop is on the right in this screenshot.

![screenshot](https://user-images.githubusercontent.com/34079124/73047237-f13b5480-3e29-11ea-9cb4-4159f7c8a904.png)

**Comment by cjbassi** [comment]
Oh yeah, so actually what I think is going on there is that ytop gets its info from procfs and it's actually showing the correct real-time CPU usage, while gotop is getting its info from `ps`  which shows the CPU usage averaged out over the lifetime of the program.

**Comment by cjbassi** [comment]
I think you're actually right though, and there might be some kind of bug in ytop since the reported CPU usage does seem pretty high.

**Comment by cjbassi** [comment]
So it just turned out to be a bug with how we were calculating the process CPU percentage, and ytop actually only uses about 1% of CPU on my laptop. It's fixed in the latest release now.
