### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by cjbassi** [cjbassi/ytop#2]
- [ ] convert the `unwrap`s to error logging and/or cleanly exit
- [x] try to print the error messages after terminal closes

**Comment by zicklag** [comment]
I *highly* suggest using [`anyhow`](docs.rs/anyhow) for error handling. If you are interested and have questions I can show you how I handle it in my terminal applications. I'm very satisfied with the setup I've settled on.

**Comment by cjbassi** [comment]
Yeah, I'm actually already using anyhow in a few places already :) Agreed it's really nice

**Comment by cjbassi** [comment]
So I'm actually kind of okay with just leaving the unwraps in at least for now, so maybe I'll come back to this later.
