### ISSUE TITLE
Add support for update intervals greater than one second

### ISSUE THREAD

**Issue by bruceg** [cjbassi/ytop#21]
There is only one option to specify the update speed, and it is in terms of the number of times *per second* it will update. This `--rate` option does not allow for fractional values, so specifying an update interval longer than one second is impossible. My personal preference would be for a `--interval` or `--delay` option like `top`, `htop`, `procinfo`, `iotop`, etc all have.

**Comment by cjbassi** [comment]
Yeah I agree, I think we should replace the rate flag with an interval flag. It would be nice if we could specify the interval as a fractional argument, since that would make some of the updating logic easier.

**Comment by cjbassi** [comment]
Alright, so the rate cli arg has been changed to interval and it now supports durations greater than 1 second. Currently it only affects the graphs including the cpu and mem graphs, but I'm open to changing it if users would prefer that. Also, it might be good to have the ability to customize the update interval of each widget.
