### ISSUE TITLE
processes: selected process is hard to read

### ISSUE THREAD

**Issue by matthiaskrgr** [cjbassi/ytop#24]
black on blue or white on blue is not always very good to read imo
![ytop](https://user-images.githubusercontent.com/476013/73034961-d62b0d80-3e46-11ea-9afa-eec5c780e196.png)
https://github.com/cjbassi/ytop/blob/master/assets/demos/demo.gif

Perhaps it would be easier on the eye if the selected line was just underlined instead of having a different background?

**Comment by cjbassi** [comment]
Yeah that does look difficult to read. Could you maybe see if a different color scheme would look better?
