### ISSUE TITLE
Too many CPUs run out of the CPU window

### ISSUE THREAD

**Issue by chipbuster** [cjbassi/ytop#26]
Required information:

Installed via AUR package ytop-git.

- rtop version (`rtop -V`): ytop 0.3.0
- The output of `uname -a`: `Linux machoke 5.4.13-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 17 Jan 2020 23:09:58 +0000 x86_64 GNU/Linux`
- Terminal emulator (e.g. iTerm or gnome terminal): Konsole
- tmux version (`tmux -V`): not using
- Any relevenat hardware info: A cpu with 16 logical cores (AMD 1800X)

Please copy or attach `~/.local/state/rtop/errors.log` if it exists and contains logs:
```
[2020-01-24][10:48:58][mio::poll][TRACE]: registering with poller                                                       
[2020-01-24][10:48:58][mio::poll][TRACE]: registering with poller
```

Bug: 

With enough CPUs, the CPU percentages run down into the disk usage segment. It's not really that bothersome, but I figured I'd file an issue.

![image](https://user-images.githubusercontent.com/4605384/73087567-4dd55880-3e98-11ea-810a-fa50ad11bddc.png)

**Comment by chipbuster** [comment]
Would you be willing to accept PRs on this project? I wouldn't mind spending some time on this.

**Comment by cjbassi** [comment]
Yes please 🙏😊
