### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by riptl** [cjbassi/ytop#31]
Would love to be able to do `cargo install ytop`!

**Comment by cjbassi** [comment]
Same! I just need to get some dependencies to release new version so I can switch off of the git branches. And also get a few more things merged upstream.

**Comment by cjbassi** [comment]
Actually, I think I'll just vendor some of the dependencies I'm waiting on and publish to crates.io sooner than later.

**Comment by cjbassi** [comment]
So it turns out you can't vendor dependencies, so I guess we're stuck waiting on some new releases for certain packages.

**Comment by tarcieri** [comment]
Which dependencies are you waiting on?

**Comment by cjbassi** [comment]
Just tui, and actually it's blocked on me fixing the pull request. I'll try to get to that when I have some time or just pull the code back into ytop for the time being so we can publish it to crates.io.

**Comment by cjbassi** [comment]
I pulled my changes back into ytop, but now we need to upgrade tui and there were some breaking changes in the latest release, so it's going to take some work to upgrade. See #69 for an issue relating to upgrading tui.

**Comment by cjbassi** [comment]
ytop is now published on crates.io!
