### ISSUE TITLE
ytop doesn't clear the screen when run on a TTY.

### ISSUE THREAD

**Issue by gardenappl** [cjbassi/ytop#36]
- ytop version: ytop 0.4.1
- The output of `uname -a`: Linux arch-laptop 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux

Normally, when you launch ytop in a terminal emulator, it clears the screen and then displays it's widgets. But when launched in a tty, it does not clear the screen, and the output of previously run commands is visible beneath the widgets.

It also doesn't clear the screen properly on exit either: in Bash, when you exit ytop, the contents remain on screen and the cursor is placed somewhere in the middle of ytop's output. (on zsh, the cursor is placed underneath the output, which looks less broken)

I would provide screenshots but for obvious reasons I can't really do that.

**Comment by cjbassi** [comment]
The screen should be cleared on startup now. But I'm not sure about how to fix the issues on exit. Maybe we can check in with crossterm for those.
