### ISSUE TITLE
unwrap_or_default not found

### ISSUE THREAD

**Issue by breuerfelix** [cjbassi/ytop#38]
hey !

this tool looks awesome and i want it :)

i try to build it with cargo from source and got the following error  
its the file src/widgets/disk.rs line 76:7

```
no method named `unwrap_or_default` found for type `std::option::Option<psutil::disk::disk_io_counters::DiskIoCounters>` i
n the current scope

note: the method `unwrap_or_default` exists but the following trait bounds were not satisfied:
           `psutil::disk::disk_io_counters::DiskIoCounters : std::default::Default`
```

i tried to build it with the night and the stable toolchain, no luck :S

am i missing something ? some library ? psutil is a python lib but i dont think that i will need this to build a cargo package :D

cheers,

felix

**Comment by cjbassi** [comment]
No you are not missing anything. I just accidentally remove something from the rust-psutil library but it should be fixed now :)

**Comment by breuerfelix** [comment]
works like a charm now :) thanks alot !
