### ISSUE TITLE
Publish binaries and packages on release

### ISSUE THREAD

**Issue by cjbassi** [cjbassi/ytop#4]
Set up github-actions to do this automatically.

Packages:
- [ ] deb package
- [ ] rpm package

Binaries:
- [x] linux-x86_64
- [x] darwin-x86_64
- [ ] windows-x86_64
- [ ] freebsd-x86_64
- [ ] openbsd-x86_64
- [ ] linux-arm*

Also publish a homebrew package at cjbassi/homebrew-ytop automatically.
Also publish AUR packages automatically.

Can use [cargo-deb](https://github.com/mmstick/cargo-deb) and [cargo-rpm](https://github.com/rustrpm/cargo-rpm).

Figure out whether to use [cargo-pkgbuild](https://github.com/kstep/cargo-pkgbuild), [cargo-makepkg](https://github.com/brandonio21/cargo-makepkg), or [cargo-arch](https://github.com/wdv4758h/cargo-arch).

**Comment by DrSensor** [comment]
Hi @cjbassi, I think you might want to recheck the PKGBUILD sha256sums again.
I just try `yay -Syu` this day then got this error:
```console
==> Making package: ytop-bin 0.4.2-1 (Rab 12 Feb 2020 04:32:10  WIB)
==> Retrieving sources...
  -> Found ytop
==> Validating source files with sha256sums...
    ytop ... FAILED
==> ERROR: One or more files did not pass the validity check!
Error downloading sources: ytop-bin
```

**Comment by cjbassi** [comment]
So I just got that error too, but then I did a clean build and then it worked for me. So I'm thinking maybe it's a yay issue? Kind of weird, let me know if you still get issues.
