### ISSUE TITLE
ytop graphics have broken spacing compared to gotop

### ISSUE THREAD

**Issue by amyspark** [cjbassi/ytop#40]
ytop graphics have a quirk, the points seem to be improperly spaced when the terminal window is maximized.

Example:

<img src="https://user-images.githubusercontent.com/13498015/74544014-2a487f80-4f25-11ea-94d0-2a8e3a24afd0.png" width="512" />

This is gotop running at the same time:
<img src="https://user-images.githubusercontent.com/13498015/74544022-2b79ac80-4f25-11ea-8374-a1f9b9824145.png" width="512" />

Required information:

- ytop version (`ytop -V`): `ytop v0.4.2 (https://github.com/cjbassi/ytop#f86926c7)`
- The output of `uname -a`: `Linux Dianakko 5.4.17-1-MANJARO #1 SMP PREEMPT Tue Feb 4 11:40:50 UTC 2020 x86_64 GNU/Linux`

Include any of the following information if relevant:

- Terminal emulator (e.g. iTerm or gnome terminal): Gnome Terminal 3.34.2
- tmux version (`tmux -V`): N/A
- Any relevenat hardware info: N/A

Please copy or attach `~/.local/state/ytop/errors.log` if it exists and contains logs: N/A

**Comment by cjbassi** [comment]
Confirmed, I have that too.

**Comment by wsturgiss** [comment]
same 
![image](https://user-images.githubusercontent.com/22747283/78913574-36e5e180-7a57-11ea-968f-8771a5f29770.png)

It can be hidden sort of, if you change the scale with `h` and `l`

**Comment by absolutelynothelix** [comment]
new graphs are *awful* compared to the good-ol' gotop: they have broken spacing and they are flickering (when graph moves dots are changing their positions)
![image](https://user-images.githubusercontent.com/52252283/79601241-31d90000-80f1-11ea-99d3-44c5085fd449.png)

**Comment by cjbassi** [comment]
I think this is fixed in the latest release of tui. There were some breaking changes in the latest release, so it's going to take some work to upgrade. See #69 for an issue relating to upgrading tui.

**Comment by cjbassi** [comment]
Should be fixed in the latest release!

**Comment by amyspark** [comment]
I can confirm it's fixed :clap:
