### ISSUE TITLE
With light background unreadable

### ISSUE THREAD

**Issue by rofrol** [cjbassi/ytop#42]
![image](https://user-images.githubusercontent.com/28787/75395039-d01ac780-58f1-11ea-9d36-1a4adb961e25.png)

Required information:

- ytop version (`ytop -V`): `ytop 0.5.1`
- The output of `uname -a`: `Linux roman-MS-7B43 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Include any of the following information if relevant:

- Terminal emulator (e.g. iTerm or gnome terminal): gnome terminal
- tmux version (`tmux -V`):
- Any relevenat hardware info:

Please copy or attach `~/.local/state/ytop/errors.log` if it exists and contains logs:

**Comment by cjbassi** [comment]
Could you see if one of the other color schemes would work better? Specifically the default dark color scheme?

**Comment by rofrol** [comment]
`default-dark` looks best, though still too light sometimes:

![default-dark](https://user-images.githubusercontent.com/28787/75397134-736ddb80-58f6-11ea-8c49-34593c3a6755.png)

monkai:

![monokai](https://user-images.githubusercontent.com/28787/75397141-79fc5300-58f6-11ea-9181-34d73cfe649b.png)

solarized-dark:

![solarized-dark](https://user-images.githubusercontent.com/28787/75397163-8385bb00-58f6-11ea-9a0e-3b09ddc556b4.png)

vice:

![vice](https://user-images.githubusercontent.com/28787/75397172-8680ab80-58f6-11ea-8974-09b4d27977f6.png)

**Comment by cjbassi** [comment]
default dark is supposed to be good for light backgrounds so if you wanna improve it and open a pr then that would be fine with me :+1:

**Comment by rofrol** [comment]
But why your light https://github.com/cjbassi/ytop/blob/master/assets/screenshots/minimal.png looks good and mine not? I am using colors from system theme in Ubuntu.

**Comment by cjbassi** [comment]
Hmm, I'm not sure. The colors do seem different, and you're also missing bold characters. Maybe a terminal issue?

**Comment by rofrol** [comment]
For bold I am using font which does not have bold.

**Comment by cjbassi** [comment]
And I think the colors just come down to your terminal colors.

**Comment by cjbassi** [comment]
I'm going to close this issue since i think this just comes down custom terminal settings.
