### ISSUE TITLE
[Feature Request] Staying at the top of processes and windows resizing

### ISSUE THREAD

**Issue by elichai** [cjbassi/ytop#84]
Hi,
This is a great tool, I currently use it daily instead of htop.
There are 2 things that bother me:
1. The processes window, it follows the highlighted process, I want to be able to always see the processes at the top of the list (that way I can know what's using the most CPU right now).

2. Being able to resize or even remove windows, for example I don't care much about always looking at the Disk Usage, but I do care about seeing more of my sensors, so I'd like to expand the Temperatures section.

Thanks :)

**Comment by cjbassi** [comment]
Hey, glad you like it. There's actually already an issue open for both of these: #53 #39 So I'm going to close as duplicate.
