### ISSUE TITLE
Always show top processes

### ISSUE THREAD

**Issue by arjobsen** [cjbassi/ytop#87]
The Processes pane "selects" the top process when ytop is started. When that process becomes idle (or just less active), the pane scrolls down together with that process. IMO it would be better to always stick to the top of the list.

Maybe if you explicitly select one of the process (with the up/down arrows) it could follow it. But this shouldn't be default behaviour because I think we are mostly interested to see the top active processes.

**Comment by cjbassi** [comment]
Agreed, there's actually already an issue open for this: #53
